"""1 migrations

Revision ID: 0a29a12cf872
Revises: 7ce134acb164
Create Date: 2024-03-18 16:07:18.531064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a29a12cf872'
down_revision: Union[str, None] = '7ce134acb164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'order_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('order_chat', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
