"""1 migrations

Revision ID: 180b14f9ebf2
Revises: 6b9d461d4d1c
Create Date: 2024-03-20 20:12:44.705508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180b14f9ebf2'
down_revision: Union[str, None] = '6b9d461d4d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name', new_column_name='name_rus')
    op.alter_column('products', 'description',
                    new_column_name='description_rus')
    op.add_column('products', sa.Column(
        'name_en', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('description_en',
                  sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name', new_column_name='name_rus')
    op.alter_column('products', 'description',
                    new_column_name='description_rus')
    op.drop_column('products', 'description_en')
    op.drop_column('products', 'name_en')
    # ### end Alembic commands ###
