"""1 migrations

Revision ID: 1e7b3e241702
Revises: 8deea74bf323
Create Date: 2024-03-20 13:02:36.792993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7b3e241702'
down_revision: Union[str, None] = '8deea74bf323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_rus', sa.String(length=64), nullable=True))
    op.add_column('categories', sa.Column('name_en', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_en')
    op.drop_column('categories', 'name_rus')
    # ### end Alembic commands ###
