"""1 migrations

Revision ID: 361be7979344
Revises: b6dc6ebc1367
Create Date: 2024-03-18 17:58:44.385969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361be7979344'
down_revision: Union[str, None] = 'b6dc6ebc1367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('deliveries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('deliveries', sa.Column('deleted_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('deliveries', sa.Column('deleted_at', sa.DateTime(), server_default=sa.text('null'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'deleted_at')
    op.drop_column('deliveries', 'deleted_flag')
    op.drop_column('deliveries', 'updated_at')
    op.drop_column('deliveries', 'created_at')
    # ### end Alembic commands ###
