"""1 migrations

Revision ID: 4a0ead63aebf
Revises: 9e4f089d0ab9
Create Date: 2024-06-20 18:37:24.945967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a0ead63aebf'
down_revision: Union[str, None] = '9e4f089d0ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sale_group', sa.BIGINT(), nullable=True),
    sa.Column('manager_group', sa.BIGINT(), nullable=True),
    sa.Column('welcome_message', sa.String(length=4048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.drop_index('ix_stores_id', table_name='stores')
    op.drop_table('stores')
    op.add_column('categories', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'stories', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'store_id')
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('opening_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('closing_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sale_group', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('welcome_message', sa.VARCHAR(length=4048), autoincrement=False, nullable=True),
    sa.Column('manager_group', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stores_pkey')
    )
    op.create_index('ix_stores_id', 'stores', ['id'], unique=False)
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
