"""1 migrations

Revision ID: 6b9d461d4d1c
Revises: e94f317c1fc8
Create Date: 2024-03-20 13:05:12.800173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9d461d4d1c'
down_revision: Union[str, None] = 'e94f317c1fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name', new_column_name='name_rus')
    op.add_column('categories', sa.Column('name_en', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name_rus', new_column_name='name')
    op.drop_column('categories', 'name_en')

    # ### end Alembic commands ###
