"""1 migrations

Revision ID: 7b24b0bb7387
Revises: 4a0ead63aebf
Create Date: 2024-06-20 18:52:13.557914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b24b0bb7387'
down_revision: Union[str, None] = '4a0ead63aebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'stories', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'store_id')
    # ### end Alembic commands ###
