"""1 migrations

Revision ID: 7ce134acb164
Revises: c7854d2eae6a
Create Date: 2024-03-18 16:06:24.519461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce134acb164'
down_revision: Union[str, None] = 'c7854d2eae6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('welcome_message', sa.String(length=4048), nullable=True))
    op.add_column('stores', sa.Column('manager_group', sa.BIGINT(), nullable=True))
    op.drop_column('stores', 'canceled_orders_chat')
    op.drop_column('stores', 'delivery_chat')
    op.drop_column('stores', 'welcome_message_bot')
    op.drop_column('stores', 'completed_orders_chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('completed_orders_chat', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('welcome_message_bot', sa.VARCHAR(length=4048), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('delivery_chat', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('canceled_orders_chat', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('stores', 'manager_group')
    op.drop_column('stores', 'welcome_message')
    # ### end Alembic commands ###
