"""1 migrations

Revision ID: 9dd3f88554de
Revises: 180b14f9ebf2
Create Date: 2024-03-21 22:59:13.626221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd3f88554de'
down_revision: Union[str, None] = '180b14f9ebf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'name', new_column_name='name_rus')
    op.add_column('deliveries', sa.Column(
        'name_en', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deliveries', 'name', new_column_name='name_rus')
    op.drop_column('deliveries', 'name_en')
    # ### end Alembic commands ###
