"""1 migrations

Revision ID: 9e4f089d0ab9
Revises: 426dacad4018
Create Date: 2024-04-13 12:31:43.319216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4f089d0ab9'
down_revision: Union[str, None] = '426dacad4018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_messages_id', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_messages_id', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
