"""1 migrations

Revision ID: b70fefd8e51a
Revises: a74d0708a759
Create Date: 2024-02-09 20:07:06.683321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70fefd8e51a'
down_revision: Union[str, None] = 'a74d0708a759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_details_id'), 'order_details', ['id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_foreign_key(None, 'orders_info', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('price_box', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price_box')
    op.drop_constraint(None, 'orders_info', type_='foreignkey')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_order_details_id'), table_name='order_details')
    # ### end Alembic commands ###
