"""1 migrations

Revision ID: bf7429f8484b
Revises: cdadc51a4c6d
Create Date: 2024-06-20 19:04:10.417984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7429f8484b'
down_revision: Union[str, None] = 'cdadc51a4c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_messages_id_store_id_fkey', 'order_messages_id', type_='foreignkey')
    op.drop_column('order_messages_id', 'store_id')
    op.add_column('orders', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'stories', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'store_id')
    op.add_column('order_messages_id', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_messages_id_store_id_fkey', 'order_messages_id', 'stories', ['store_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
