"""1 migrations

Revision ID: e94f317c1fc8
Revises: 1e7b3e241702
Create Date: 2024-03-20 13:04:50.159309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94f317c1fc8'
down_revision: Union[str, None] = '1e7b3e241702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_rus')
    op.drop_column('categories', 'name_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_en', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('name_rus', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
